name: Lint - YAML
on: [push, pull_request]

jobs:
  yamllint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ibiqlik/action-yamllint@v3
